# -*- coding: utf-8 -*-
"""EXNO 5 APPDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-YQ573bneWBqvspEo7AfE5cndsqgaFjs
"""

pip install dash plotly pandas

import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import plotly.express as px
import pandas as pd

import plotly.graph_objects as px
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset('tips')
#DISPLAY FIRST 5 RECORDS

plot = px.Figure(data=[px.Scatter(
    x=df['day'],
    y=df['tip'],
    mode='markers',)
])

# Add dropdown

plot.show()

x = df['total_bill']
y = df['tip']

#IMPLEMENT SCATTER PLOT
plot.show()

import plotly.express as px

# data to be plotted

# plotting the figure


fig.show()

import plotly.express as px

# Loading the data


# Creating the bar chart


fig.show()

import plotly.express as px

# using the dataset


# plotting the histogram

# showing the plot

import plotly.express as px

# Loading the iris dataset